manifest:
  version: 0.7
  remotes:
    - name: adi-innersource
      url-base: https://github.com/adi-innersource
    - name: adi
      url-base: https://github.com/analogdevicesinc
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  defaults:
    remote: zephyrproject-rtos
  projects:
    - name: zephyr
      remote: adi-innersource
      revision: adi-main
      import: true
    - name: canopennode
      revision: zephyr
  self:
    path: ardagvmotor
