manifest:
  version: 0.7
  remotes:
    - name: innersource-ioan
      url-base: https://github.com/Ioan-Dragomir_adi
    - name: analogdevicesinc
      url-base: https://github.com/analogdevicesinc
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  defaults:
    remote: zephyrproject-rtos
  projects:
    - name: zephyr
      remote: innersource-ioan
      revision: feature/max32662-can
      import: true
    - name: canopennode
      revision: zephyr
  self:
    path: ardagvmotor
