/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: AGV_CIA402_ProfileVelocity_Barebones.xdd
        File Version: 1

        Created:      2025-01-13 11:03:07 AM
        Created By:   
        Modified:     2025-01-29 12:54:09 PM
        Modified By:  

    Device Info:
        Vendor Name:  Analog Devices Inc.
        Vendor ID:    0xFFFF1234
        Product Name: AGV Arduino Motor Control
        Product ID:   123

        Description:  
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_TIME 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 16


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    char x1008_manufacturerDeviceName[22];
    char x1009_manufacturerHardwareVersion[5];
    char x100A_manufacturerSoftwareVersion[19];
    uint32_t x1012_COB_IDTimeStampObject;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1019_synchronousCounterOverflowValue;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1402_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1403_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1602_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1603_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A03_TPDOMappingParameter;
} OD_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    uint16_t x2122_TMC9660SUPPLY_VOLTAGE;
    uint16_t x6040_controlword;
    uint16_t x6041_statusword;
    int8_t x6060_modesOfOperation;
    int8_t x6061_modesOfOperationDisplay;
    int32_t x6063_positionActualValue;
    int32_t x6069_velocitySensorActualValue;
    int32_t x606B_velocityDemandValue;
    int32_t x606C_velocityActualValue;
    int16_t x6071_targetTorque;
    uint16_t x6072_maxTorque;
    uint8_t x607E_polarity;
    uint32_t x6081_profileVelocity;
    uint32_t x6083_profileAcceleration;
    uint32_t x6084_profileDeceleration;
    int16_t x6086_motionProfileType;
    char x6089_positionNotationIndex[2];
    uint8_t x608A_positionDimensionIndex;
    int8_t x608B_velocityNotationIndex;
    int8_t x608C_velocityDimensionIndex;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t encoderIncrements;
        uint32_t motorRevolutions;
    } x608F_positionEncoderResolution;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t encoderIncrementsPerSecond;
        uint32_t motorRevolutionsPerSecond;
    } x6090_velocityEncoderResolution;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t motorRevolutions;
        uint32_t shaftRevolutions;
    } x6091_gearRatio;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t feed;
        uint32_t shaftRevolutions;
    } x6092_feedConstant;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t numerator;
        uint32_t feedConstant;
    } x6093_positionFactor;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t numerator;
        uint32_t divisor;
    } x6094_velocityEncoderFactor;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t numerator;
        uint32_t divisor;
    } x6095_velocityFactor1;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t numerator;
        uint32_t divisor;
    } x6096_velocityFactor2;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t numerator;
        uint32_t divisor;
    } x6097_accelerationFactor;
    int32_t x60F8_maxSlippage;
    int32_t x60FF_targetVelocity;
    uint32_t x6502_supportedDriveModes;
    uint32_t x67FF_singleDeviceType;
} OD_RAM_t;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif
extern OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1006 &OD->list[4]
#define OD_ENTRY_H1007 &OD->list[5]
#define OD_ENTRY_H1008 &OD->list[6]
#define OD_ENTRY_H1009 &OD->list[7]
#define OD_ENTRY_H100A &OD->list[8]
#define OD_ENTRY_H1012 &OD->list[9]
#define OD_ENTRY_H1014 &OD->list[10]
#define OD_ENTRY_H1015 &OD->list[11]
#define OD_ENTRY_H1017 &OD->list[12]
#define OD_ENTRY_H1018 &OD->list[13]
#define OD_ENTRY_H1019 &OD->list[14]
#define OD_ENTRY_H1200 &OD->list[15]
#define OD_ENTRY_H1280 &OD->list[16]
#define OD_ENTRY_H1400 &OD->list[17]
#define OD_ENTRY_H1401 &OD->list[18]
#define OD_ENTRY_H1402 &OD->list[19]
#define OD_ENTRY_H1403 &OD->list[20]
#define OD_ENTRY_H1600 &OD->list[21]
#define OD_ENTRY_H1601 &OD->list[22]
#define OD_ENTRY_H1602 &OD->list[23]
#define OD_ENTRY_H1603 &OD->list[24]
#define OD_ENTRY_H1800 &OD->list[25]
#define OD_ENTRY_H1801 &OD->list[26]
#define OD_ENTRY_H1802 &OD->list[27]
#define OD_ENTRY_H1803 &OD->list[28]
#define OD_ENTRY_H1A00 &OD->list[29]
#define OD_ENTRY_H1A01 &OD->list[30]
#define OD_ENTRY_H1A02 &OD->list[31]
#define OD_ENTRY_H1A03 &OD->list[32]
#define OD_ENTRY_H2122 &OD->list[33]
#define OD_ENTRY_H6040 &OD->list[34]
#define OD_ENTRY_H6041 &OD->list[35]
#define OD_ENTRY_H6060 &OD->list[36]
#define OD_ENTRY_H6061 &OD->list[37]
#define OD_ENTRY_H6063 &OD->list[38]
#define OD_ENTRY_H6069 &OD->list[39]
#define OD_ENTRY_H606B &OD->list[40]
#define OD_ENTRY_H606C &OD->list[41]
#define OD_ENTRY_H6071 &OD->list[42]
#define OD_ENTRY_H6072 &OD->list[43]
#define OD_ENTRY_H607E &OD->list[44]
#define OD_ENTRY_H6081 &OD->list[45]
#define OD_ENTRY_H6083 &OD->list[46]
#define OD_ENTRY_H6084 &OD->list[47]
#define OD_ENTRY_H6086 &OD->list[48]
#define OD_ENTRY_H6089 &OD->list[49]
#define OD_ENTRY_H608A &OD->list[50]
#define OD_ENTRY_H608B &OD->list[51]
#define OD_ENTRY_H608C &OD->list[52]
#define OD_ENTRY_H608F &OD->list[53]
#define OD_ENTRY_H6090 &OD->list[54]
#define OD_ENTRY_H6091 &OD->list[55]
#define OD_ENTRY_H6092 &OD->list[56]
#define OD_ENTRY_H6093 &OD->list[57]
#define OD_ENTRY_H6094 &OD->list[58]
#define OD_ENTRY_H6095 &OD->list[59]
#define OD_ENTRY_H6096 &OD->list[60]
#define OD_ENTRY_H6097 &OD->list[61]
#define OD_ENTRY_H60F8 &OD->list[62]
#define OD_ENTRY_H60FF &OD->list[63]
#define OD_ENTRY_H6502 &OD->list[64]
#define OD_ENTRY_H67FF &OD->list[65]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[3]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[4]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[5]
#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[6]
#define OD_ENTRY_H1009_manufacturerHardwareVersion &OD->list[7]
#define OD_ENTRY_H100A_manufacturerSoftwareVersion &OD->list[8]
#define OD_ENTRY_H1012_COB_IDTimeStampObject &OD->list[9]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[10]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[11]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[12]
#define OD_ENTRY_H1018_identity &OD->list[13]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue &OD->list[14]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[15]
#define OD_ENTRY_H1280_SDOClientParameter &OD->list[16]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[17]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[18]
#define OD_ENTRY_H1402_RPDOCommunicationParameter &OD->list[19]
#define OD_ENTRY_H1403_RPDOCommunicationParameter &OD->list[20]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[21]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[22]
#define OD_ENTRY_H1602_RPDOMappingParameter &OD->list[23]
#define OD_ENTRY_H1603_RPDOMappingParameter &OD->list[24]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[25]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[26]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[27]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[28]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[29]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[30]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[31]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[32]
#define OD_ENTRY_H2122_TMC9660SUPPLY_VOLTAGE &OD->list[33]
#define OD_ENTRY_H6040_controlword &OD->list[34]
#define OD_ENTRY_H6041_statusword &OD->list[35]
#define OD_ENTRY_H6060_modesOfOperation &OD->list[36]
#define OD_ENTRY_H6061_modesOfOperationDisplay &OD->list[37]
#define OD_ENTRY_H6063_positionActualValue &OD->list[38]
#define OD_ENTRY_H6069_velocitySensorActualValue &OD->list[39]
#define OD_ENTRY_H606B_velocityDemandValue &OD->list[40]
#define OD_ENTRY_H606C_velocityActualValue &OD->list[41]
#define OD_ENTRY_H6071_targetTorque &OD->list[42]
#define OD_ENTRY_H6072_maxTorque &OD->list[43]
#define OD_ENTRY_H607E_polarity &OD->list[44]
#define OD_ENTRY_H6081_profileVelocity &OD->list[45]
#define OD_ENTRY_H6083_profileAcceleration &OD->list[46]
#define OD_ENTRY_H6084_profileDeceleration &OD->list[47]
#define OD_ENTRY_H6086_motionProfileType &OD->list[48]
#define OD_ENTRY_H6089_positionNotationIndex &OD->list[49]
#define OD_ENTRY_H608A_positionDimensionIndex &OD->list[50]
#define OD_ENTRY_H608B_velocityNotationIndex &OD->list[51]
#define OD_ENTRY_H608C_velocityDimensionIndex &OD->list[52]
#define OD_ENTRY_H608F_positionEncoderResolution &OD->list[53]
#define OD_ENTRY_H6090_velocityEncoderResolution &OD->list[54]
#define OD_ENTRY_H6091_gearRatio &OD->list[55]
#define OD_ENTRY_H6092_feedConstant &OD->list[56]
#define OD_ENTRY_H6093_positionFactor &OD->list[57]
#define OD_ENTRY_H6094_velocityEncoderFactor &OD->list[58]
#define OD_ENTRY_H6095_velocityFactor1 &OD->list[59]
#define OD_ENTRY_H6096_velocityFactor2 &OD->list[60]
#define OD_ENTRY_H6097_accelerationFactor &OD->list[61]
#define OD_ENTRY_H60F8_maxSlippage &OD->list[62]
#define OD_ENTRY_H60FF_targetVelocity &OD->list[63]
#define OD_ENTRY_H6502_supportedDriveModes &OD->list[64]
#define OD_ENTRY_H67FF_singleDeviceType &OD->list[65]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = OD_CNT_TIME;\
    (config).ENTRY_H1012 = OD_ENTRY_H1012;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_ENTRY_H1019;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
