#include "301/CO_config.h"

#undef CO_CONFIG_NMT
#define CO_CONFIG_NMT (CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE | CO_CONFIG_FLAG_TIMERNEXT)

#undef CO_CONFIG_HB_CONS
// #define CO_CONFIG_HB_CONS (CO_CONFIG_HB_CONS_ENABLE)
#define CO_CONFIG_HB_CONS (0)

// ?? does this do anyth?
//#undef CO_CONFIG_TIME
//#define CO_CONFIG_TIME (0)

#undef CO_CONFIG_SYNC
#define CO_CONFIG_SYNC (CO_CONFIG_SYNC_ENABLE | CO_CONFIG_GLOBAL_RT_FLAG_CALLBACK_PRE | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT | CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)

// add CO_CONFIG_PDO_OD_IO_ACCESS | CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC as well?
#undef CO_CONFIG_PDO
#define CO_CONFIG_PDO (CO_CONFIG_RPDO_ENABLE | CO_CONFIG_TPDO_ENABLE | CO_CONFIG_RPDO_TIMERS_ENABLE | CO_CONFIG_TPDO_TIMERS_ENABLE | CO_CONFIG_PDO_SYNC_ENABLE | CO_CONFIG_GLOBAL_RT_FLAG_CALLBACK_PRE | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT)

#undef CO_CONFIG_STORAGE
#define CO_CONFIG_STORAGE (0)

// Will do LED logic manually because of the weird red LED behaviour
#undef CO_CONFIG_LEDS
#define CO_CONFIG_LEDS (CO_CONFIG_LEDS_ENABLE | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT)

// Actually don't need LSS, but will need a heartbeat
#undef CO_CONFIG_LSS
#define CO_CONFIG_LSS (0)

#undef CO_CONFIG_DEBUG
#define CO_CONFIG_DEBUG (CO_CONFIG_DEBUG_COMMON)
